=== learnerJavaheihei/286/dist/gameserver/data/costumes_mul_collect.dtd
<?xml version="1.0" encoding="utf-8"?>
    <!ELEMENT list (costumes_suit_list|mul_collect)*>
        <!ELEMENT costumes_suit_list (suit)*>
            <!ELEMENT suit (costumeId)*>
            <!ATTLIST suit
                    num CDATA #REQUIRED>
                <!ELEMENT costumeId (#PCDATA)>
        <!ELEMENT mul_collect (skillList)*>
        <!ATTLIST mul_collect
                id CDATA #REQUIRED>
            <!ELEMENT skillList (skill)*>
                <!ELEMENT skill (#PCDATA)>
                <!ATTLIST skill
                        id CDATA #REQUIRED
                        level CDATA #REQUIRED>

=== learnerJavaheihei/286/dist/gameserver/data/costumes_mul_collect.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "costumes_mul_collect.dtd">
<list>
    <costumes_suit_list>
        <suit num="1">
            <costumeId>16</costumeId>
            <costumeId>21</costumeId>
            <costumeId>26</costumeId>
            <costumeId>71</costumeId>
        </suit>
        <suit num="2">
            <costumeId>1</costumeId>
            <costumeId>46</costumeId>
            <costumeId>76</costumeId>
            <costumeId>31</costumeId>
            <costumeId>67</costumeId>
        </suit>
        <suit num="3">
            <costumeId>89</costumeId>
            <costumeId>93</costumeId>
            <costumeId>97</costumeId>
            <costumeId>101</costumeId>
            <costumeId>105</costumeId>
            <costumeId>109</costumeId>
        </suit>
        <suit num="4">
            <costumeId>13</costumeId>
            <costumeId>38</costumeId>
            <costumeId>82</costumeId>
        </suit>
        <suit num="5">
            <costumeId>122</costumeId>
            <costumeId>119</costumeId>
            <costumeId>137</costumeId>
            <costumeId>140</costumeId>
            <costumeId>128</costumeId>
        </suit>
        <suit num="6">
            <costumeId>116</costumeId>
            <costumeId>134</costumeId>
            <costumeId>113</costumeId>
            <costumeId>125</costumeId>
            <costumeId>131</costumeId>
        </suit>
        <suit num="7">
            <costumeId>53</costumeId>
            <costumeId>58</costumeId>
            <costumeId>63</costumeId>
            <costumeId>68</costumeId>
            <costumeId>73</costumeId>
            <costumeId>78</costumeId>
        </suit>
        <suit num="8">
            <costumeId>54</costumeId>
            <costumeId>91</costumeId>
            <costumeId>95</costumeId>
            <costumeId>145</costumeId>
        </suit>
        <suit num="9">
            <costumeId>64</costumeId>
            <costumeId>99</costumeId>
            <costumeId>111</costumeId>
            <costumeId>79</costumeId>
        </suit>
        <suit num="10">
            <costumeId>83</costumeId>
            <costumeId>87</costumeId>
            <costumeId>103</costumeId>
            <costumeId>107</costumeId>
        </suit>
        <suit num="11">
            <costumeId>145</costumeId>
            <costumeId>143</costumeId>
            <costumeId>147</costumeId>
            <costumeId>149</costumeId>
            <costumeId>151</costumeId>
        </suit>
        <suit num="12">
            <costumeId>146</costumeId>
            <costumeId>144</costumeId>
            <costumeId>148</costumeId>
            <costumeId>150</costumeId>
            <costumeId>152</costumeId>
        </suit>
    </costumes_suit_list>
    <mul_collect id="1">
        <skillList>
            <skill id="59346" level="1"/>
        </skillList>
    </mul_collect>
    <mul_collect id="2">
        <skillList>
            <skill id="59345" level="1"/>
            <skill id="59346" level="1"/>
        </skillList>
    </mul_collect>
    <mul_collect id="3">
        <skillList>
            <skill id="59345" level="1"/>
            <skill id="59346" level="2"/>
        </skillList>
    </mul_collect>
    <mul_collect id="4">
        <skillList>
            <skill id="59345" level="2"/>
            <skill id="59346" level="2"/>
            <skill id="59347" level="1"/>
            <skill id="59348" level="1"/>
        </skillList>
    </mul_collect>
    <mul_collect id="5">
        <skillList>
            <skill id="59345" level="2"/>
            <skill id="59346" level="3"/>
            <skill id="59347" level="1"/>
            <skill id="59348" level="1"/>
        </skillList>
    </mul_collect>
    <mul_collect id="6">
        <skillList>
            <skill id="59345" level="3"/>
            <skill id="59346" level="3"/>
            <skill id="59347" level="1"/>
            <skill id="59348" level="1"/>
        </skillList>
    </mul_collect>
    <mul_collect id="7">
        <skillList>
            <skill id="59345" level="3"/>
            <skill id="59346" level="4"/>
            <skill id="59347" level="1"/>
            <skill id="59348" level="1"/>
        </skillList>
    </mul_collect>
    <mul_collect id="8">
        <skillList>
            <skill id="59345" level="4"/>
            <skill id="59346" level="4"/>
            <skill id="59347" level="2"/>
            <skill id="59348" level="2"/>
        </skillList>
    </mul_collect>
    <mul_collect id="9">
        <skillList>
            <skill id="59345" level="4"/>
            <skill id="59346" level="5"/>
            <skill id="59347" level="2"/>
            <skill id="59348" level="2"/>
        </skillList>
    </mul_collect>
    <mul_collect id="10">
        <skillList>
            <skill id="59345" level="5"/>
            <skill id="59346" level="5"/>
            <skill id="59347" level="2"/>
            <skill id="59348" level="2"/>
        </skillList>
    </mul_collect>
    <mul_collect id="11">
        <skillList>
            <skill id="59345" level="5"/>
            <skill id="59346" level="6"/>
            <skill id="59347" level="2"/>
            <skill id="59348" level="2"/>
        </skillList>
    </mul_collect>
    <mul_collect id="12">
        <skillList>
            <skill id="59345" level="6"/>
            <skill id="59346" level="6"/>
            <skill id="59347" level="3"/>
            <skill id="59348" level="3"/>
        </skillList>
    </mul_collect>
</list>
